### PR TITLE
Fix custom breakpoints

### PR DESCRIPTION
**Pull request by palicko**
Hey @nandorojo 
I've noticed, that custom breakpoints are not working, when used on web without SSR/Next.js.

Please take a look at this PR as this should fix it.

BTW huge thanks for this repo!

### CODE REVIEW

**Comment by nandorojo** [comment]
Hey thanks for this. I don't currently have custom breakpoint support, since there's a big re-factor underway (Fresnel-2 PR branch) that will change how the provider and theme are created. I have an issue [here](https://github.com/nandorojo/dripsy/issues/25) to track adding custom breakpoints once the refactor is done. 

It'll be a breaking change of the current API, so I've held off on adding it until Fresnel-2 is merged to master.

With all that said, I'll see if we can add these in for now, until the refactor is merged. I just have to make sure the breakpoints aren't used anywhere else that's missing from your changes first. Thanks for the PR!

**Comment by balasan** [comment]
Would love to see this PR merged.
Had to create a patch to over-write the hard-coded breakpoints for now...
Other than this the library has been working great!

**Comment by nandorojo** [comment]
Yeah, I feel your pain on this, I'm sorry that it hasn't been merged.

It isn't for lack of interest. Rather, it would require a breaking change that would be pretty disruptive, due to the way SSR support works on web. I'll try to think of a creative way around that so that we can get this merged. Thanks for the patience!

**Comment by nandorojo** [comment]
Okay, I think I thought of a simpler solution. At the root of your app, just do this, before importing any Dripsy code:

```js
// App.js
import { setBreakpoints } from 'dripsy'

setBreakpoints([400, 792, 968, 1200]) // replace with your custom breakpoints

import { DripsyProvider } from 'dripsy'
```

Please let me know if this works if you come across it! I can't guarantee it will, since I'm not fully sure what order the breakpoints on web get created in with fresnel. It's possible it won't, but we'll see. This is currently an experimental feature.

**Pull request closed without merging**
