### PR TITLE
Added in useResponsiveValue hook

### LINKED ISSUE #9: useResponsiveValue hook
Can be tied with the current `useBreakpointIndex` hook in `src/css`.

Reference: https://github.com/system-ui/theme-ui/tree/master/packages/match-media

### PR DESCRIPTION
**Pull request by cmaycumber**
This commit resolves #9 by adding a useResponsiveValue hook that leverages the useBreakpointIndex hook and creates a brief example of it in the project example.

### CODE REVIEW

**Comment by nandorojo** [comment]
This looks great! Only step left is to add docs, but this will go with #5

**Comment by nandorojo** [comment]
Published in `0.5.2`. Thanks so much for the great work.

**Comment by cmaycumber** [comment]
Thanks! Look forward to helping out more

**Comment by nandorojo** [comment]
100%!

**Pull request merged**
