### PR TITLE
Fresnel 2

### PR DESCRIPTION
**Pull request by nandorojo**
# What

This PR adds server-side rendering support (Next.js, Gatsby, etc.) to Dripsy. This means Dripsy's style-once-use-anywhere approach can be maturely used in important, production apps.

# To-Do

- [x] Web performance tests
- [x] Test on iOS/Android
- [x] Test on web without SSR
- [x] Document
- [x] Update Next.js example
- [ ] Add custom breakpoint support (separate PR, breaking change)

### CODE REVIEW

**Comment by nandorojo** [comment]
To close #1

**Comment by cmaycumber** [comment]
What was the error you were running into with expo start? When testing expo start mine was having trouble resolving react and noticed that it wasn't installed as a dev dependency so I installed that and was able to get it to bundle. But am running into an error with ColorModeProvider inside ThemeProvider. I can pull this PR later and try to fix it.

**Comment by nandorojo** [comment]
Ah that must be it. I removed the react dev dependency since the next.js example said there were two competing versions of React and wouldn't run. The next.js example is simlinked with `yarn link dripsy`. Maybe I can keep react as a dev dependency in the root and remove it from the next example.

**Comment by cmaycumber** [comment]
We could do that or switch to a monorepo approach if we are going that direction anyway with @dripsy/srr. I think the ColorModeProvider would be an easy fix we just need to use our own ThemeProvider rather than the one from theme-ui like so. 

Grabbed the following code from [https://github.com/samjbmason/theme-ui-native](https://github.com/samjbmason/theme-ui-native)

```javascript
export const ThemeProvider = ({ theme, children }) =>
  createElement(ThemeContext.Provider, { value: { theme } }, children)
```

**Comment by nandorojo** [comment]
Where are you seeing that error, could you post a screenshot?

As of now, I'm actually using the same code for web and SSR after all. If `Platform.OS === 'web'` is the condition I'm using. So for the time being I'll probably not use the SSR package, but it's likely that'll end up happening down the road. Definitely open to a monorepo.

**Comment by nandorojo** [comment]
Also, I changed the API from `ThemeProvider` to `DripsyProvider` to compare the difference, mind changing your import?

**Comment by cmaycumber** [comment]
Good call. It does look likes it's the DripsyProvider causing the issue.

**Comment by cmaycumber** [comment]
Here's the screenshot: 
Screen Shot 2020-07-24 at 10 17 48 AM

**Comment by cmaycumber** [comment]
I think I was able to solve this. I ended up adding both react and react-native as peer dependencies for dripsy and things started to work. It's weird the error seemed pretty unrelated maybe I had something else set up wrong I'm not sure. 

Either way, I'll push to this PR once I test android. Just let me know if it's working on your end as well.

**Comment by cmaycumber** [comment]
I spoke too soon, I think I had a cached version on my simulator while I tested the web one. I'm still running into issues. I'll try to get something together that works for both.

**Comment by nandorojo** [comment]
Sounds good, I can try some stuff out in a bit as well.

**Comment by nandorojo** [comment]
Relevant conversation on the Fresnel repo: https://github.com/artsy/fresnel/issues/144

**Comment by cmaycumber** [comment]
I'll push to a new branch on my fork with the same name if you need to take anything from it in the meantime. I ended up removing the metro config and just using the tarball for the time being because it seems to work for IOS while the metro config is giving me a lot of trouble. Ideally, I imagine we can find a better way that is stable and allows for better local development so you don't have to re-pack the lib every time.

**Comment by nandorojo** [comment]
Yeah, there's definitely room to get a better local dev process going. The babel module resolver worked for me using normal expo web, but I had to use simlinks to test next.js, so it all became a bit jumbled.

**Comment by cmaycumber** [comment]
I got a version working and pushed it up to my fork fresnel-2 branch. I haven't tested the next-example but the normal example is working well.

**Comment by nandorojo** [comment]
Awesome, thank you! I'll see if I can get it to work with the next one.

**Comment by nandorojo** [comment]
I'd also like to test the performance on this PR for web. I'm not sure what the best way to profile is with react, but my guess would be to render tons of components, each with responsive styles, and compare speed/load times vs importing the same components from RNW directly.

**Comment by cmaycumber** [comment]
This might be pretty helpful for this: [React Profile API](https://reactjs.org/docs/profiler.html)

**Comment by nandorojo** [comment]
Custom breakpoints for web is going to require a breaking API change, so I'm going to leave it for a separate PR once this is merged + published.

**Comment by cmaycumber** [comment]
Do you want me to make a PR between my fresnel-2 branch and this one? I had to do some re-working of the different config files in the example application. Not sure what's necessary to keep or what works with m branch. 

I'd love to start with some of the performance tests once we make sure it's working on the different devices/frameworks.

**Comment by nandorojo** [comment]
@cmaycumber sure, that might make the most sense. The files that are in the actual dripsy src/ (not example apps) should follow the ones in this PR, correct?

**Comment by cmaycumber** [comment]
@nandorojo Yeah correct. I only changed the example app and moved react/react-native to peer dependencies. 

On a side note, I tested Dripsy on the Gatsby project I'm working on using SSR and it seems to be working. I'm not super familiar with fresnel but it does generate a lot of additional DOM nodes. Not sure if this is intended behavior or not but it makes sense based on how we are creating components with SSR rn, I thought that fresnel mentioned some sort of cleanup (maybe it's gatsby?). 

Other than that it seemed to be working like a charm.

**Comment by nandorojo** [comment]
> it does generate a lot of additional DOM nodes.

...yeah, this is definitely the down-side trade-off of using Fresnel, and it's why I want to do some rigorous speed testing, especially with Next.js 9.5's new profiling.

The way Fresnel works, in order to get every element on the server to match those of the client, is to render every item 4 times (one for each breakpoint, technically,) hiding the DOM nodes that aren't available with CSS. 

Then, on the client, Fresnel uses the JS `match-media` API to clean up the nodes that aren't inside of the breakpoint. Of all the trade-offs, this has seemed to be the best way 1) get dripsy to work with SSR, and 2) avoid using the deprecated `className` prop, stay in the "JS world" rather than using CSS, as recommended by @necolas and the future React Native community in general.

**Comment by nandorojo** [comment]
Could we leave the `src/components` file in the other PR? It seems that there are still some unresolved components there.

**Comment by nandorojo** [comment]
For performance profiling: https://reactjs.org/blog/2016/11/16/react-v15.4.0.html#profiling-components-with-chrome-timeline

**Comment by nandorojo** [comment]
I'm pretty sure Fresnel handles this, but just to be clear, what happens if a child runs a side effect? Will it execute for all 4 children? I think the answer is no, since they'll get cleaned up before the useEffect runs...?

Should test that to be sure.

**Comment by cmaycumber** [comment]
That's a valid point we should make sure that those parent nodes aren't re-rendering or anything. I'm sure this can be done in parallel with performance testing.

**Comment by nandorojo** [comment]
Closing #12 for now with this PR, since I've added a `styled` function. I think it's the best option to prevent re-renders from inline styles until records/tuples are around.

**Comment by nandorojo** [comment]
I'm testing this out in a real-world app now.

I'm seeing this error when I resize the window the first time:

image

I'm running it in expo + next, and am rendering many components.

**Comment by cmaycumber** [comment]
I'm going to try to pull it into another one of my projects and see if I can reproduce anything similar.

 Either way, it might be good to switch out the logic to your suggested method to prevent any unnecessary re-renders.

**Comment by nandorojo** [comment]
Agreed, I updated that locally, I'll push / publish it shortly.

**Comment by cmaycumber** [comment]
I also got a yarn workspace version of this branch working that should solve the local development issues. Whenever we get this branch ironed out I'll make a new PR.

**Comment by nandorojo** [comment]
This might be overkill optimization, but it might also be useful to move the `useDimensions` listener to the provider, and then share it with other components as a single state. I'm not sure if there are implications to setting up hundreds of listeners, but I am noticing that using `useDimensions` when rendering many components makes changing screen size slow.

**Comment by nandorojo** [comment]
From my experience using this so far, I don't seem to be getting any performance bottlenecks from Fresnel. But I'm still testing it out in a real-world app and will confirm shortly.

**Comment by cmaycumber** [comment]
That's awesome let me know how that goes. I'm sure it can always be improved down the line if need be as well.

**Comment by nandorojo** [comment]
I'm using `useDimensions` from `@react-native-community/hooks`, which rerenders on every screen change, it seems. Maybe a debounced hook could help, I'll see once I've tested more.

There is one problem with fresnel I've seen: it wraps every element in a fresnel div, which means setting `flex: 1` to an element does nothing, since it has a fresnel parent.

**Comment by cmaycumber** [comment]
Any ideas on how to solve that? I could see that being pretty inconvenient in some scenarios. Maybe some sort of override styling to the fresnel container would be able to fix that in rare scenarios.

**Comment by nandorojo** [comment]
Yeah it's not great. It only happens if the dripsy component has responsive styles (ie it has an array of styles for one of its `sx` keys.)

My current work-around has been to wrap elements in a `View` without responsive style. Not great.

We could maybe pass certain style props onto the `fresnel` parent, like `flex`. Basically it matters for any styles that are relevant to the parent. I'll have to think it over, because it could have some unintended side effects to pass styles to a container and a child.

**Comment by nandorojo** [comment]
Alternatively, we could put a `webContainerStyle` or `webContainerSx` prop that passes styles to the fresnel parent. Less magical, but you do have more control. I'll have to think it over.

**Comment by cmaycumber** [comment]
Yeah for sure. I'm really down for either. I can't really think of a perfect solution for this one. We'll definitely have to test it either way. 

That workaround is probably fine for the meantime. Sure it'll cause some cluttering + extra dom nodes but I don't think it's the end of the world.

**Comment by nandorojo** [comment]
@cmaycumber any shot you could push your yarn workspaces to this branch? I'm making some rapid changes to address the problem above, it would make it much easier to test with a workspace.

**Comment by nandorojo** [comment]
I also came up with a solution to solve the glitchiness of changing screen sizes. It involves using css values on web and JS on native, all with one API.

I put together a rough snack [here](https://snack.expo.io/@nandorojo/use-responsive-universal) to play around with.

## `useResponsive`

```jsx
// before

const { width } = useDimensions().window
const cardWidth = width / 4

return <View sx={{ width: cardWidth }} />
```

```jsx
// after

const { vw } = useResponsive()
const cardWidth = vw(25) // 25% width of the screen

return <View sx={{ width: cardWidth }} />
```

On web, this returns a `25vw` CSS value, and on native, it accesses the actual `Dimensions` width.

## `useCalc`

This is still just an idea, and it's a bit cumbersome, but it lets us make complex-ish calculations for responsive sizes that support CSS on web and JS on native.

```jsx
const { calc, add, subtract } = useCalc()
const { vw } = useResponsive()

const cardWidth = calc(add(vw(25), 10)) // 10px + 25% of the screen
const cardHeight = calc(add(vw(25), subtract(10, vw(1)))

return <View sx={{ width: cardWidth }} />
```

The code for `vw` and `vh` is as simple as:

```jsx
const useResponsive = () => {
  const { width, height } = useDimensions({
  __shouldDisableListenerOnWeb: true
 }).window

  const vw = (percent: number) => {
    return Platform.select({
      web: `${percent}vw`,
      default: percent * width / 100 as any
    })
  }
  const vh = (percent: number) => {
    return Platform.select({
      web: `${percent}vh`,
      default: percent * height / 100 as any
    })
  }
}
```

I'll play around with this more in my own app and see how I like using the API. It'd be opt-in only anyway. It slightly goes against the idea of using no CSS values in RNW, but I think it's a fair escape hatch. Plus, the API you interact with is still in JS.

**Comment by cmaycumber** [comment]
Yeah, I'd love to push that up. One sec I need to make sure that I don't have any rogue changes in it. 

Another note bob currently doesn't watch the dripsy folder so I would recommend having two terminals so that you can re-compile the code when you make a change and it should update in the examples. I'm going to work on a solution that solves this with nodemon later on.

**Comment by nandorojo** [comment]
I'm currently solving the aforementioned issue of styling the fresnel `div` node like this:

Screen Shot 2020-09-14 at 7 24 16 PM

It seems to be working well in my real app, so I'll push it to this branch shortly. It's currently published on the `container-sx` npm tag if you want to try it.

**Comment by nandorojo** [comment]
I've been using this in a real app for a bit now. It's working really well, very fast. I still plan on optimizing it by using `StyleSheet` instead of inline styles and some things like that, but overall, I'm very happy with the performance.

The **one** performance bottleneck I'm seeing is coming from resizing the window. My best guess is that this is due to hundreds of `match-media` listeners getting pinged as it drags. I wonder if we could inspect the fresnel code and get to the bottom of that. A solution could be setting up one listener in the fresnel provider that wraps the app, and passing the current breakpoint down to individual items via context.

**Comment by cmaycumber** [comment]
I like the idea of passing down the breakpoint through context. That sounds like it would greatly benefit the performance and seems like the best practice solution to me.

Overall that's awesome. What do you think needs to get finished on this branch before it gets merged into master? I'd love to help knock some of those out.

**Comment by nandorojo** [comment]
As far as the `fresnel-2` branch is concerned, I think the final thing to solve is the performance on resize. I'm looking into the fresnel code to see where they have that logic. Hopefully the bottleneck isn't hard to find. Besides that, I think it's all good.

A useful way to test this is to have a lot of images with text overlays (say 120) on a page in rows and then resize the screen.

**Comment by cmaycumber** [comment]
Sweet. Have you tried the context being passed down yet? That's something I can try to experiment with later today.

**Comment by nandorojo** [comment]
I haven't – I'm actually not sure how Fresnel is setting up the listeners / updating the state on breakpoint changes. I'd definitely like to try a fork that passes this through the context to see if that affects the performance. If that isn't it, I'll keep digging. 

The good news is, it isn't _that_ bad when the window resizes. Also, users don't resize their windows many times when they visit websites. But I would like it to be on par with native CSS performance if possible.

**Comment by nandorojo** [comment]
I just added a style reset to the `div` node from fresnel. [(Commit)](https://github.com/nandorojo/dripsy/pull/14/commits/f53c5312a5ec7dcfa87ae2763d74dc08ffad036d)

I added the same style reset that RNW has for its views. 

I also forwarded the `flex` value from `breakpointStyle` ([or `style`](https://github.com/nandorojo/dripsy/pull/14/commits/9acb06cce608489717809f87c3c07b655f3ccf42)). I'm not sure if this will have any unintended effects, but the idea is that, if this component has a `flex` property, it should get forwarded to the `div` wrapping it. Otherwise, a component with `flex: 1` won't stretch to its parent if it has any other responsive values. I'm not set on keeping this at all as a default, but I'm going to play around with it to see what the effect is. If we remove this as a default, then you'd need to set `webContainerSx={{ flex: 1 }}` pretty often. But I also don't want unintended styles. So I'll see how it works.

**Comment by nandorojo** [comment]
There is one final change for this library that I am going back-and-forth on: should the library always use Fresnel for web, or only if someone specifies `ssr: true` when initializing Dripsy? I'm pretty close to thinking yes, but I'll jot down my thoughts first.

# Current state

Currently, if `Platform.OS === 'web'`, Dripsy uses `fresnel` to render responsive styles. That means that, whether you're using Expo with Next, React Native Web SPA, or any variation, as long as you're on web, Dripsy uses Fresnel for you, and completely ignores the `Dimensions` API.

## Benefits of this approach

**1.** No need for developers to set `ssr: true`, works out of the box (+ `SSRStyleReset` injected in the `head`)
**2.** Platform-centric development. Anyone using dripsy for web uses it the same way and sees the same thing. This can probably help with debugging things and building features that everyone consistently wants.
**3.** Consistent development. If you turned `ssr: true` to `ssr: false` and your entire app styles messed up, you'd be pretty pissed. By having it be consistent on all web projects, we can ensure that adoption of Dripsy feels incremental.

## Downsides of this approach

**1.** Fresnel is only needed for SSR. If you have a single-page application that loads on the client, then React Native's `Dimensions` API works just fine for you. In fact, it's technically preferred, since you're staying closer to JS / React Native.
**2.** As I've alluded to quite a bit above, wrapping every element with a `div` has unintended consequences when you're doing the following: setting a `maxWidth` on an item, setting `flex: 1` to stretch a row, etc.

The workaround is to use `webContainerSx`. You use that prop to add styles to the `div` that is wrapping your dripsy component. This can be a bit confusing sometimes, since it isn't super obvious. You mostly have to learn to realize that, if your flexbox isn't working properly, you should probably play with `webContainerSx`. 

The question is, should someone that doesn't even want to use SSR have to deal with this added layer of API complexity?

(For the record, it's not that bad. But it's not the most intuitive, since you don't see the `div` in your code as you try to debug. A funny idea could be to toss a yellow warning to the web console if you use any of the styles that could cause bugs. Dripsy could then export a `suppressAnnoyingWarning` function that you can call at the root of your app when you understand how it works. lol)

**3.** More DOM nodes. This has created no performance downfall for me, so I don't think it's a big concern for the modern web. But I figure it's worth mentioning in case that's a big concern.

----

Ultimately, I think the move is to use Fresnel for all web projects. Having a single API to maintain for web would be best, and it will make the development experience consistent across projects. There is a slight learning curve to using `webContainerSx`, but as a community grows around Dripsy, everyone will be in it together and will help the few people who don't realize it at first. I'll mention it on the docs as an anti-pitch when we spin off a separate website.

The need to use Fresnel in the first place comes down to the decision from RNW's creator to deprecate the `className` prop. Given that most apps are moving towards a hybrid of static- and server-side generation, it puts developers in a tough place. As a result, even the best solutions will require trade-offs. But I think the Dripsy/Fresnel approach is as good as it will get.

**Comment by nandorojo** [comment]
Updated readme to reflect new approach for SSR.

**Comment by nandorojo** [comment]
I plan on merging this tomorrow.

**Pull request merged**
