### PR TITLE
Added support for yarn workspaces that allows for easy development + dependency sharing

### PR DESCRIPTION
**Pull request by cmaycumber**
# Notes

- Had to change version of dripsy package to a number from '0.7.4-fresnel-2' to support yarn workspaces.
- Dripsy needs to be rebuilt manually using ```$ bob prepare``` when changes are made but the changes will be picked up by the example applications.
- Added in resolutions in workspace root for theme-ui 0.4.0-rc.1 versions.

### CODE REVIEW

**Comment by cmaycumber** [comment]
One thing that I thought might be nice to consider is creating an examples folder with the following structure similar to other open-source projects like NextJS:

```
examples
└ next-example
└ expo-example
└ gatsby-example
```

We could add additional examples as we feel the need to.

**Comment by nandorojo** [comment]
> One thing that I thought might be nice to consider is creating an examples folder with the following structure similar to other open-source projects like NextJS:
> 
> 
> 
> ```
> 
> examples
> 
> └ next-example
> 
> └ expo-example
> 
> └ gatsby-example
> 
> ```
> 
> 
> 
> We could add additional examples as we feel the need to. 

I definitely agree. That said, I would want to differentiate our dev examples and the examples shown for adoption purposes. The dev examples require quite a bit of tooling in Babel and such, but the `examples` folder should probably just install from npm and work more simply.

**Comment by nandorojo** [comment]
This PR could make for a useful git repo in general that explains how to make a monorepo for expo + nextjs + external packages.

**Comment by cmaycumber** [comment]
> I definitely agree. That said, I would want to differentiate our dev examples and the examples shown for adoption purposes. The dev examples require quite a bit of tooling in Babel and such, but the examples folder should probably just install from npm and work more simply.

I agree with this. That seems to be the standard. We can probably create a new repo with those examples.

> This PR could make for a useful git repo in general that explains how to make a monorepo for expo + nextjs + external packages.

That's a solid idea. I've definitely had trouble finding more complex monorepos that are using expo/next/gatsby.

**Comment by nandorojo** [comment]
Think you could pull in my latest changes in `css`? Seems like I'm getting some conflicts, sorry about that.

**Comment by nandorojo** [comment]
Should be able to get this merged afterwards!

**Comment by cmaycumber** [comment]
> Should be able to get this merged afterwards!

Yes, definitely! I'll do this ASAP

**Comment by cmaycumber** [comment]
Should be gtg. Give it a review and let me know @nandorojo

**Comment by nandorojo** [comment]
Question - shouldn't the example apps be using the code pointed to by the`react-native` field in the `package.json`? I thought that's what the point of that field was, but for some reason I don't think they do.

**Comment by nandorojo** [comment]
Also, I believe the fresnel-2 branch already implemented fixes for the `css` function and `useResponsiveValue`, I think this branch was just behind a few commits from before the fixes.

**Comment by cmaycumber** [comment]
> Question - shouldn't the example apps be using the code pointed to by the react-native field in the package.json? I thought that's what the point of that field was, but for some reason I don't think they do.

By react-native in the package.json do you mean the local version for the example or the one that's a peer dependency in dripsy? Yarn workspaces attempts to hoist as many packages as it can to the top-level node modules to avoid duplicating them. It looks like we have two separate versions of react-native for the examples and they seem to be keeping them in there local node-modules on my end. Are you seeing something different? 

> Also, I believe the fresnel-2 branch already implemented fixes for the css function and useBreakpointIndex, I think this branch was just behind a few commits from before the fixes.

Sorry, these are bad commit messages. I was simply trying to update to the latest version of fresnel-2 in a rush this morning. Let me take another pass and make sure that all the files in the src for fresnel-2 match one for one to the files in dripsy package for this branch.

**Comment by nandorojo** [comment]
Sorry I should have been more clear. I'm not referring to the React Native dependency.

Every npm package has a `main` field in its package.json. This tells apps where to look for the files.

I'm pretty sure that, in addition to `main`, they can have a `react-native` field. If you're using a React Native app, it will use the file that the `react-native` field points to, instead of `main`.

This has been my experience in the past, and it's the reason `bob` includes a `react-native` field on init.

See line 8:

image

Shouldn't it not be necessary to watch changes from bob, since the examples should be pointed to the source code field? I can try logging some things in `src/index` to see if they are.

**Comment by cmaycumber** [comment]
Ahh, I see what you are saying. 

That's a good point. Yes, if that's the case then bob shouldn't have to rebuild at all. I'm not sure if it currently works that's a valid point. 

I'll try to help debug this as well. I plan on taking a peek at the react-navigation monorepo they handle this I do believe.

**Comment by cmaycumber** [comment]
Do you know whether or not the react-native field is getting picked up when building the iOS or Android version of the application?

I think the reason might be webpack when it's getting bundled for the web.

**Comment by cmaycumber** [comment]
I ended up getting the examples working without compiling bob after tweaking the webpack configs for both the examples inspired after taking inspiration from the react-navigation repo. I'll go ahead and merge that code in. 

I'm still not sure why the react-native field doesn't work on the web but I assume it has something to do with it not detecting that it's in an RN env. When I switched the field to "browser", webpack tried to compile it but threw and error due to it not having a ts-loader.

**Comment by nandorojo** [comment]
This is really great stuff.

Is there any shot you could make a quick list of the steps needed to get a monorepo with expo and next working? I'd love to be able to reproduce this again. It would also help me understand how this repo's structure will work a little better.

If it's too much trouble to do that, I can try to piece it together from your commits, but I figured I'd ask while it's still fresh in your mind. I see this monorepo style becoming my default workflow.

**Comment by nandorojo** [comment]
Every expo monorepo I've found seems to be utilizing `lerna`:


https://github.com/Fried-Chicken/expo-monorepo

I'm pretty new to monorepo structure, so I'm not sure if that would be best for this project or not, but I'll check it out a bit more.

**Comment by cmaycumber** [comment]
I'll gladly put something together.

I'll create a separate repo with reproduction steps on my GitHub. 

I'm also super down to throw Lerna in as well. I think it will definitely help manage all the separate packages as we add them to dripsy.

**Comment by nandorojo** [comment]
Yeah I think a separate minimal repo is the move. I can help test it out ASAP, since I'm currently working on turning my next + expo project into a monorepo.

**Comment by nandorojo** [comment]
I've been getting acquainted with Lerma today. Super useful, I think it'll be a nice addition.

**Comment by nandorojo** [comment]
Got this example working: https://github.com/nandorojo/expo-next-monorepo

It probably doesn't work for external packages that are published on npm, since I don't compile the TS from the dependencies. But for an internal app's sharing code, it works easily!

**Comment by cmaycumber** [comment]
That looks great! Super clean and minimal. 

I like how it doesn't require the weird webpack config the other one was using. I wonder if expo transpire modules would work well with this monorepo.

**Comment by nandorojo** [comment]
Yeah, the benefit of this example vs a lib like dripsy is that we can point the `@shared/components` `main` field and `types` field directly to the TS file, since the app consuming it is definitely using TS. For external packages, this usually isn't the case, so we rely on something like bob to handle the building, and point the `main` to the JS it outputs.

**Comment by nandorojo** [comment]
Just realized my monorepo example didn't have the actual app pushed, I just updated it.

**Comment by cmaycumber** [comment]
@nandorojo Is a monorepo still something that we want to consider or do you think we should move forward with just the current structure for now?

**Comment by nandorojo** [comment]
I think a monorepo makes sense.

**Comment by cmaycumber** [comment]
Alright cool. That will make the docs simpler as well. I can re-create this PR based on the most recent version Dripsy.

Not sure what the best way to get the final version in is. The conversion to the monorepo will obviously cause a lot of conflicts. Especially with any outstanding PR's. I'll probably close my components PR and re-create that one as well if we get a monorepo PR in.

**Comment by nandorojo** [comment]
I think that makes sense. A monorepo that solves the problem of testing live source code would be super helpful for adding features. Not sure if that's part of your plan in the change to a monorepo or not. But it seems like once it's 1) a Lerna monorepo and 2) source code can be used in examples in real-time, other PRs/changes become far easier.

**Pull request closed without merging**
